In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1


Introduction to Tensors

Pytorch tensors are created using torch.tensor()


In [5]:
# scalar

scalar = torch.tensor(7)
scalar.ndim # 0
scalar.shape # torch.Size([])

0

In [6]:
# Get tensor back as Python int
scalar.item() # 7

7

In [8]:
# Vector
vector = torch.tensor([7,7])
vector # tensor([7, 7])

vector.ndim # 1
vector.shape # torch.Size([2])

torch.Size([2])

In [9]:
# MATRIX

matrix = torch.tensor([[7,8],[9,10]])
matrix.ndim # 2
matrix[1] # tensor([ 9, 10])
matrix.shape # torch.Size([2, 2])
# normally write matrix and tensors in capital letters for variables

MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX.ndim # 2
MATRIX[1] # tensor([ 9, 10])
MATRIX.shape # torch.Size([2, 2])

In [12]:
# tensor
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR.ndim # 3
TENSOR.shape # torch.Size([1, 3, 3])
TENSOR[0] # tensor([[1, 2, 3],
          #        [4, 5, 6],
          #        [7, 8, 9]])
# tensor[1]  IndexError: index 1 is out of bounds for dimension 0 with size 1

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random Tensors

Neural networks often begin with tensors filled with random numbers and then adjust them to fit the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [13]:
# Create a random tensor of size (3,4)
R_T = torch.rand(3,4)
R_T.shape # torch.Size([3, 4])
R_T.ndim # 2
R_T

tensor([[0.9860, 0.6767, 0.1189, 0.9057],
        [0.6125, 0.1806, 0.4117, 0.2812],
        [0.3918, 0.6527, 0.5354, 0.4459]])

In [15]:
rand_image_tensor = torch.rand(3,224,244)
rand_image_tensor.shape # torch.Size([224, 224, 3])
rand_image_tensor.ndim # 3
rand_image_tensor   

tensor([[[0.6179, 0.9990, 0.7227,  ..., 0.4224, 0.8996, 0.6188],
         [0.7699, 0.4883, 0.6598,  ..., 0.8151, 0.3729, 0.6116],
         [0.3880, 0.1699, 0.0942,  ..., 0.8553, 0.0906, 0.9535],
         ...,
         [0.7418, 0.2317, 0.2633,  ..., 0.8081, 0.3939, 0.3656],
         [0.9128, 0.0595, 0.0134,  ..., 0.1069, 0.9977, 0.6289],
         [0.7976, 0.8404, 0.4607,  ..., 0.8763, 0.9091, 0.3838]],

        [[0.9376, 0.3583, 0.9762,  ..., 0.9835, 0.2372, 0.8074],
         [0.6435, 0.7208, 0.2828,  ..., 0.9394, 0.0839, 0.6472],
         [0.9472, 0.7673, 0.0788,  ..., 0.2766, 0.2609, 0.9209],
         ...,
         [0.5303, 0.2097, 0.9893,  ..., 0.2992, 0.3763, 0.5296],
         [0.1207, 0.9393, 0.6784,  ..., 0.8331, 0.3911, 0.2105],
         [0.3317, 0.3645, 0.7214,  ..., 0.3788, 0.7716, 0.6380]],

        [[0.9779, 0.4969, 0.0344,  ..., 0.4729, 0.3358, 0.7497],
         [0.6037, 0.8857, 0.5083,  ..., 0.8393, 0.1576, 0.4898],
         [0.8105, 0.2381, 0.3994,  ..., 0.5425, 0.3232, 0.

In [17]:
# Create a tensor with all zeros
ZEROS = torch.zeros(3,4)
ZEROS.dtype # torch.float32
ZEROS

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
# Create a tensor with all ones

ONES = torch.ones(3,4)
ONES.dtype # torch.float32
ONES

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])