In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1


Introduction to Tensors

Pytorch tensors are created using torch.tensor()

In [3]:
# scalar

scalar = torch.tensor(7)
scalar.ndim # 0
scalar.shape # torch.Size([])

torch.Size([])

In [4]:
# Get tensor back as Python int
scalar.item() # 7

7

In [5]:
# Vector
vector = torch.tensor([7,7])
vector # tensor([7, 7])

vector.ndim # 1
vector.shape # torch.Size([2])

torch.Size([2])

In [6]:
# MATRIX

matrix = torch.tensor([[7,8],[9,10]])
matrix.ndim # 2
matrix[1] # tensor([ 9, 10])
matrix.shape # torch.Size([2, 2])
# normally write matrix and tensors in capital letters for variables

MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX.ndim # 2
MATRIX[1] # tensor([ 9, 10])
MATRIX.shape # torch.Size([2, 2])

torch.Size([2, 2])

In [7]:
# tensor
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR.ndim # 3
TENSOR.shape # torch.Size([1, 3, 3])
TENSOR[0] # tensor([[1, 2, 3],
          #        [4, 5, 6],
          #        [7, 8, 9]])
# tensor[1]  IndexError: index 1 is out of bounds for dimension 0 with size 1

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random Tensors

Neural networks often begin with tensors filled with random numbers and then adjust them to fit the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [8]:
# Create a random tensor of size (3,4)
R_T = torch.rand(3,4)
R_T.shape # torch.Size([3, 4])
R_T.ndim # 2
R_T

tensor([[0.4935, 0.0987, 0.0935, 0.3964],
        [0.1860, 0.7529, 0.5627, 0.9852],
        [0.2751, 0.1639, 0.4882, 0.6674]])

In [9]:
rand_image_tensor = torch.rand(3,224,244)
rand_image_tensor.shape # torch.Size([224, 224, 3])
rand_image_tensor.ndim # 3
rand_image_tensor   

tensor([[[1.1656e-01, 6.8627e-01, 1.0596e-01,  ..., 8.2768e-01,
          4.0763e-01, 1.9636e-01],
         [9.9665e-01, 7.9570e-01, 7.5745e-01,  ..., 4.4081e-01,
          4.9233e-01, 9.2068e-02],
         [9.0261e-01, 7.6226e-01, 3.8261e-02,  ..., 1.4087e-01,
          1.5726e-01, 6.1302e-01],
         ...,
         [1.3226e-01, 9.7331e-01, 4.3349e-01,  ..., 2.5380e-01,
          7.1695e-01, 5.1545e-01],
         [6.4336e-01, 2.8480e-02, 9.3198e-01,  ..., 4.6310e-01,
          5.7243e-01, 9.1721e-01],
         [2.9696e-01, 9.8824e-01, 5.4416e-01,  ..., 2.0485e-01,
          6.7732e-01, 1.6889e-01]],

        [[4.4785e-01, 2.4636e-02, 9.1867e-01,  ..., 5.9223e-01,
          6.5587e-02, 5.7424e-01],
         [6.9100e-01, 5.4247e-01, 1.4455e-01,  ..., 1.6657e-01,
          9.3675e-01, 1.7715e-01],
         [6.6416e-01, 6.7544e-01, 6.2591e-01,  ..., 6.6656e-01,
          5.5365e-01, 8.0216e-01],
         ...,
         [8.5289e-01, 9.3950e-01, 4.6347e-01,  ..., 7.8344e-01,
          3.416

In [10]:
# Create a tensor with all zeros
ZEROS = torch.zeros(3,4)
ZEROS.dtype # torch.float32
ZEROS

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [11]:
# Create a tensor with all ones

ONES = torch.ones(3,4)
ONES.dtype # torch.float32
ONES

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [12]:
# Use torch.arange()

range_tensor = torch.arange(1,11)
range_tensor # tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

step_range_tensor = torch.arange(1,11,2)
step_range_tensor # tensor([1, 3, 5, 7, 9])

one_to_thousand_step_77 = torch.arange(1,1001,77)
one_to_thousand_step_77 # tensor([  1,  78, 155, 232, 309, 386, 463, 540, 617, 694, 771, 848, 925])

zero_range_tensors = torch.zeros_like(range_tensor)
zero_range_tensors # tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

one_range_tensors = torch.ones_like(range_tensor)
one_range_tensors # tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Tensor Datatypes

**Note** Tensor datatypes is one of the three big errors you'll run into with PyTorch & Deep learning:


In [13]:
float_32_tensor = torch.tensor([3.0,6.0,9.0]) # default dtype is float32
float_32_tensor.dtype # torch.float32

tensor_param_showcase = torch.tensor(data=[3.0,6.0,9.0],dtype=torch.float64,
                                     # device='none',
                                     # requires_grad means if you want to track gradients for tensor operations
                                     requires_grad=False)
float_64_tensor = torch.tensor([3.0,6.0,9.0],dtype=torch.float64)
float_64_tensor.dtype # torch.float64

torch.float64

In [14]:
float_16_tensor = float_32_tensor.type(torch.float16) # convert float32 to float16
test_tensor =float_16_tensor * float_32_tensor # tensor([ 9., 36., 81.], dtype=torch.float16)
test_tensor.dtype

torch.float32

In [15]:
some_tensor = torch.rand(3,4)
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype} ")
print(f"Device tensor is stored on: {some_tensor.device} ")
print(f"Size of tensor: {some_tensor.size()} ")
# some_tensor = some_tensor.to("cuda")
# print(f"Device tensor is stored on: {some_tensor.device} ")


tensor([[0.9192, 0.0100, 0.8376, 0.7011],
        [0.9057, 0.7593, 0.2468, 0.8945],
        [0.7407, 0.8737, 0.3499, 0.0276]])
Datatype of tensor: torch.float32 
Device tensor is stored on: cpu 
Size of tensor: torch.Size([3, 4]) 


## Tensor Operations

Addition
Subtraction
Multiplication
Division
Matrix Multiplication

In [16]:

tensor = torch.tensor([1,2,3])
tensor + 100 # tensor([101, 102, 103])
tensor * 10 # tensor([10, 20, 30])
tensor - 10 # tensor([-9, -8, -7])
tensor / 10 # tensor([0.1000, 0.2000, 0.3000])
tensor // 10 # tensor([0, 0, 0])
tensor ** 2 # tensor([1, 4, 9]) 
tensor.matmul(tensor) # tensor(14)
second_tensor = torch.tensor([[1,2,3],[4,5,6]])
second_tensor.matmul(second_tensor.T) # tensor([[14, 32],

tensor([[14, 32],
        [32, 77]])

In [17]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 813 μs, sys: 1.07 ms, total: 1.89 ms
Wall time: 1.56 ms


In [18]:
%%time
tensor.matmul(tensor)

CPU times: user 20 μs, sys: 5 μs, total: 25 μs
Wall time: 24.1 μs


tensor(14)

In [19]:
tensor_B = torch.tensor([[1,2],[3,4],[5,6]])
tensor_B.shape # torch.Size([3, 2])
tensor_B.T # tensor(([[1, 3, 5],
          #        [2, 4, 6]]))
          

tensor([[1, 3, 5],
        [2, 4, 6]])

Finding the min, max, mean, sum, etc (tensor aggregation)

In [26]:
x = torch.arange(0,100,10)
x # tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

torch.min(x) # tensor(0)
torch.max(x) # tensor(90)
x.min() # tensor(0)
x.max() # tensor(90)
x.dtype  # torch.int64
x = x.to(dtype=torch.float32) # need to do otherwise will get error
torch.mean(x)  # tensor(45.)
torch.argmax(x) # tensor(9)
torch.argmin(x) # tensor(0)


0

In [34]:
y = torch.tensor([[1,2,3],[3,5,7]])
y.shape
y[1][2]
y.argmax() # tensor(5)

tensor(5)

## Resharping, stacking, shaping, and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tesnor
* Unsqueeze - adds a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certan way