In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1


Introduction to Tensors

Pytorch tensors are created using torch.tensor()

In [3]:
# scalar

scalar = torch.tensor(7)
scalar.ndim # 0
scalar.shape # torch.Size([])

torch.Size([])

In [4]:
# Get tensor back as Python int
scalar.item() # 7

7

In [5]:
# Vector
vector = torch.tensor([7,7])
vector # tensor([7, 7])

vector.ndim # 1
vector.shape # torch.Size([2])

torch.Size([2])

In [6]:
# MATRIX

matrix = torch.tensor([[7,8],[9,10]])
matrix.ndim # 2
matrix[1] # tensor([ 9, 10])
matrix.shape # torch.Size([2, 2])
# normally write matrix and tensors in capital letters for variables

MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX.ndim # 2
MATRIX[1] # tensor([ 9, 10])
MATRIX.shape # torch.Size([2, 2])

torch.Size([2, 2])

In [7]:
# tensor
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR.ndim # 3
TENSOR.shape # torch.Size([1, 3, 3])
TENSOR[0] # tensor([[1, 2, 3],
          #        [4, 5, 6],
          #        [7, 8, 9]])
# tensor[1]  IndexError: index 1 is out of bounds for dimension 0 with size 1

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random Tensors

Neural networks often begin with tensors filled with random numbers and then adjust them to fit the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [8]:
# Create a random tensor of size (3,4)
R_T = torch.rand(3,4)
R_T.shape # torch.Size([3, 4])
R_T.ndim # 2
R_T

tensor([[0.2847, 0.0218, 0.9098, 0.1319],
        [0.2090, 0.2658, 0.4724, 0.8538],
        [0.6993, 0.5761, 0.2674, 0.7252]])

In [9]:
rand_image_tensor = torch.rand(3,224,244)
rand_image_tensor.shape # torch.Size([224, 224, 3])
rand_image_tensor.ndim # 3
rand_image_tensor   

tensor([[[8.5791e-01, 2.0130e-01, 7.8213e-01,  ..., 6.5178e-01,
          2.9808e-01, 8.6008e-01],
         [3.7343e-01, 9.2687e-01, 7.5836e-01,  ..., 5.2487e-01,
          6.5328e-01, 2.7168e-04],
         [7.4855e-01, 1.0131e-01, 2.7552e-01,  ..., 8.2258e-01,
          4.9153e-02, 6.6170e-01],
         ...,
         [7.0741e-01, 6.1752e-01, 3.2767e-01,  ..., 9.9465e-03,
          3.4962e-01, 4.8787e-02],
         [4.4411e-01, 9.2131e-01, 6.3526e-01,  ..., 7.0875e-01,
          8.4753e-02, 9.6421e-02],
         [6.1648e-01, 6.4327e-01, 1.4991e-02,  ..., 2.9281e-02,
          8.1410e-01, 2.4932e-01]],

        [[5.1212e-01, 9.1089e-01, 2.1913e-01,  ..., 6.5425e-01,
          2.8148e-03, 5.2230e-02],
         [7.9812e-01, 6.1359e-01, 3.0375e-01,  ..., 1.7688e-01,
          6.8392e-01, 2.1793e-01],
         [3.8489e-01, 3.1258e-01, 5.7640e-01,  ..., 9.3464e-01,
          7.0225e-01, 6.8078e-01],
         ...,
         [4.7562e-01, 4.9369e-01, 6.3490e-01,  ..., 1.5998e-01,
          5.699

In [10]:
# Create a tensor with all zeros
ZEROS = torch.zeros(3,4)
ZEROS.dtype # torch.float32
ZEROS

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [11]:
# Create a tensor with all ones

ONES = torch.ones(3,4)
ONES.dtype # torch.float32
ONES

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [12]:
# Use torch.arange()

range_tensor = torch.arange(1,11)
range_tensor # tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

step_range_tensor = torch.arange(1,11,2)
step_range_tensor # tensor([1, 3, 5, 7, 9])

one_to_thousand_step_77 = torch.arange(1,1001,77)
one_to_thousand_step_77 # tensor([  1,  78, 155, 232, 309, 386, 463, 540, 617, 694, 771, 848, 925])

zero_range_tensors = torch.zeros_like(range_tensor)
zero_range_tensors # tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

one_range_tensors = torch.ones_like(range_tensor)
one_range_tensors # tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Tensor Datatypes

**Note** Tensor datatypes is one of the three big errors you'll run into with PyTorch & Deep learning:


In [13]:
float_32_tensor = torch.tensor([3.0,6.0,9.0]) # default dtype is float32
float_32_tensor.dtype # torch.float32

tensor_param_showcase = torch.tensor(data=[3.0,6.0,9.0],dtype=torch.float64,
                                     # device='none',
                                     # requires_grad means if you want to track gradients for tensor operations
                                     requires_grad=False)
float_64_tensor = torch.tensor([3.0,6.0,9.0],dtype=torch.float64)
float_64_tensor.dtype # torch.float64

torch.float64

In [14]:
float_16_tensor = float_32_tensor.type(torch.float16) # convert float32 to float16
test_tensor =float_16_tensor * float_32_tensor # tensor([ 9., 36., 81.], dtype=torch.float16)
test_tensor.dtype

torch.float32

In [15]:
some_tensor = torch.rand(3,4)
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype} ")
print(f"Device tensor is stored on: {some_tensor.device} ")
print(f"Size of tensor: {some_tensor.size()} ")
# some_tensor = some_tensor.to("cuda")
# print(f"Device tensor is stored on: {some_tensor.device} ")


tensor([[0.6026, 0.7163, 0.6850, 0.5368],
        [0.3881, 0.0375, 0.2762, 0.6890],
        [0.3923, 0.1720, 0.2166, 0.1471]])
Datatype of tensor: torch.float32 
Device tensor is stored on: cpu 
Size of tensor: torch.Size([3, 4]) 


## Tensor Operations

Addition
Subtraction
Multiplication
Division
Matrix Multiplication

In [16]:

tensor = torch.tensor([1,2,3])
tensor + 100 # tensor([101, 102, 103])
tensor * 10 # tensor([10, 20, 30])
tensor - 10 # tensor([-9, -8, -7])
tensor / 10 # tensor([0.1000, 0.2000, 0.3000])
tensor // 10 # tensor([0, 0, 0])
tensor ** 2 # tensor([1, 4, 9]) 
tensor.matmul(tensor) # tensor(14)
second_tensor = torch.tensor([[1,2,3],[4,5,6]])
second_tensor.matmul(second_tensor.T) # tensor([[14, 32],

tensor([[14, 32],
        [32, 77]])

In [17]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 746 μs, sys: 1.2 ms, total: 1.95 ms
Wall time: 1.75 ms


In [18]:
%%time
tensor.matmul(tensor)

CPU times: user 56 μs, sys: 40 μs, total: 96 μs
Wall time: 84.9 μs


tensor(14)

In [19]:
tensor_B = torch.tensor([[1,2],[3,4],[5,6]])
tensor_B.shape # torch.Size([3, 2])
tensor_B.T # tensor(([[1, 3, 5],
          #        [2, 4, 6]]))
          

tensor([[1, 3, 5],
        [2, 4, 6]])

Finding the min, max, mean, sum, etc (tensor aggregation)

In [20]:
x = torch.arange(0,100,10)
x # tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

torch.min(x) # tensor(0)
torch.max(x) # tensor(90)
x.min() # tensor(0)
x.max() # tensor(90)
x.dtype  # torch.int64
x = x.to(dtype=torch.float32) # need to do otherwise will get error
torch.mean(x)  # tensor(45.)
torch.argmax(x) # tensor(9)
torch.argmin(x) # tensor(0)


tensor(0)

In [21]:
y = torch.tensor([[1,2,3],[3,5,7]])
y.shape
y[1][2]
y.argmax() # tensor(5)

tensor(5)

## Resharping, stacking, shaping, and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tesnor
* Unsqueeze - adds a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certan way

In [22]:
x = torch.tensor([1,2,3,4,5])
x.ndim # 1
x.shape # torch.Size([5])
x.reshape(5) # tensor([1, 2, 3, 4, 5])
x.reshape(1,5) # tensor([[1, 2, 3, 4, 5]])
x.reshape(5,1) # tensor([[1],
            #         [2],
            #         [3],
            #         [4],
            #         [5]])
            
z = torch.stack((x,x),dim=0)
z # tensor([[1, 2, 3, 4, 5],
    #       [1, 2, 3, 4, 5]])
z.shape # torch.Size([2, 5])

y = torch.stack((y,y),dim=1)
y # tensor([[[1, 2, 3],
    #         [1, 2, 3]],
    #        [[3, 5, 7],
    #         [3, 5, 7]]])
     # 
torch.hstack((y,y)) # basically torch.stack with dim = 0
torch.vstack((y,y)) # basically torch.stack with dim = 1

tensor([[[1, 2, 3],
         [1, 2, 3]],

        [[3, 5, 7],
         [3, 5, 7]],

        [[1, 2, 3],
         [1, 2, 3]],

        [[3, 5, 7],
         [3, 5, 7]]])

In [23]:
x =torch.zeros(2,1,2,1,2)
x.shape # torch.Size([2, 1, 2, 1, 2])
x.squeeze() 
x.squeeze().shape  # torch.Size([2, 2, 2])

x= torch.zeros(9)
x.shape # torch.Size([9])
x.unsqueeze(dim=0).shape # torch.Size([1, 9])
x.unsqueeze(dim=1).shape # torch.Size([9, 1])
x.unsqueeze(dim=1) # tensor([[0.], 9 times vertically



tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]])

In [24]:
x_original = torch.rand(size=(224,224,3))
x_original.shape # torch.Size([224, 224, 3])
print(x_original)
# Permute the original tensor to rearrange the axis (or dim)
x_permuted = x_original.permute(2,0,1) # change axis 0 to 2, 1 to 0, 2 to 1
x_permuted.shape # torch.Size([3, 224, 224])
print(x_permuted)

tensor([[[0.0769, 0.2838, 0.2422],
         [0.7131, 0.6144, 0.6116],
         [0.8841, 0.8945, 0.3983],
         ...,
         [0.5513, 0.6059, 0.8113],
         [0.8052, 0.1604, 0.1760],
         [0.3105, 0.3307, 0.6721]],

        [[0.1745, 0.6262, 0.7358],
         [0.5018, 0.5554, 0.0145],
         [0.1912, 0.4810, 0.9744],
         ...,
         [0.0899, 0.2878, 0.8853],
         [0.1985, 0.9843, 0.9216],
         [0.8299, 0.8185, 0.9451]],

        [[0.1554, 0.7938, 0.9962],
         [0.5688, 0.2051, 0.3571],
         [0.6356, 0.0706, 0.7824],
         ...,
         [0.7200, 0.1010, 0.3962],
         [0.2641, 0.6255, 0.4018],
         [0.2408, 0.3225, 0.1327]],

        ...,

        [[0.1172, 0.4125, 0.8656],
         [0.1549, 0.9689, 0.6441],
         [0.9149, 0.7367, 0.3209],
         ...,
         [0.2930, 0.1754, 0.3309],
         [0.3443, 0.5968, 0.0097],
         [0.9593, 0.2275, 0.4052]],

        [[0.7639, 0.8430, 0.5583],
         [0.0674, 0.3092, 0.6111],
         [0.

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [25]:
x = torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [34]:
arr = np.arange(1,0,8.0)
tensor = torch.from_numpy(arr) # convert numpy array to tensor, numpy default dtype is float64 while torch is float32 

tensor = torch.ones(9)
tensor.numpy() # convert tensor to numpy array

array([1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)